schema=XmlRewriteIntent.v1
mapping=com.tongsr.kaleido.sample.StaticProbeView|com.tongsr.kaleido.sample.kf77a70.Cf77a70ae59
site=layout/protected_probe_layout.xml/element[1]|com.tongsr.kaleido.sample.StaticProbeView|com.tongsr.kaleido.sample.kf77a70.Cf77a70ae59
